options:
  openstack-origin:
    type: string
    default: antelope
    description: |
      Repository from which to install. May be one of the following:
      distro (default), ppa:somecustom/ppa, a deb url sources entry,
      or a supported Ubuntu Cloud Archive e.g.
      .
      cloud:<series>-<openstack-release>
      cloud:<series>-<openstack-release>/updates
      cloud:<series>-<openstack-release>/staging
      cloud:<series>-<openstack-release>/proposed
      .
      See https://wiki.ubuntu.com/OpenStack/CloudArchive for info on which
      cloud archives are available and supported.
      .
      NOTE: updating this setting to a source that is known to provide
      a later version of OpenStack will trigger a software upgrade unless
      action-managed-upgrade is set to True.
  rabbit-user:
    type: string
    default: trove
    description: Username used to access rabbitmq queue.
  rabbit-vhost:
    type: string
    default: openstack
    description: RabbitMQ virtual host to request access on rabbitmq-server.
  database-user:
    type: string
    default: trove
    description: Username for Trove database access.
  database:
    type: string
    default: trove
    description: Database name for Trove.

  # Trove control plane config options.
  enable-secure-rpc-messaging:
    type: boolean
    default: true
    description: |
      Should RPC messaging traffic be secured by encryption.
  taskmanager-rpc-encr-key:
    type: string
    default: ""
    description: |
      The key (OpenSSL aes_cbc) used to encrypt RPC messages sent to
      trove-taskmanager, used by trove-api.
  instance-rpc-encr-key:
    type: string
    default: ""
    description: |
      The key (OpenSSL aes_cbc) used to encrypt RPC messages sent to
      guest instance from trove-taskmanager and the messages sent from
      guest instance to trove-conductor. This key is generated by
      trove-taskmanager automatically and is injected into the guest
      instance when creating.
  inst-rpc-key-encr-key:
    type: string
    default: ""
    description: |
      The database encryption key to encrypt per-instance PRC encryption
      key before storing to Trove database.
  management-networks:
    type: string
    default: ""
    description: |
      List of IDs for management networks which should be attached to the instance
      regardless of what NICs are specified in the create API call. Currently only
      one management network is allowed.
  management-security-groups:
    type: string
    default: ""
    description: |
      Comma-separated list of the security group IDs that are applied on the
      management port of the database instance.
  ip-regex:
    type: string
    default: ""
    description: |
      List IP addresses that match this regular expression.
  ip-black-list-regex:
    type: string
    default: ""
    description: |
      Exclude IP addresses that match this regular expression.
  cinder-volume-type:
    type: string
    default: ""
    description: |
      Volume type to use when provisioning a Cinder volume.
  max-accepted-volume-size:
    type: int
    default: 10
    description: |
      The default maximum volume size (in GB) for an instance.
  max-volumes-per-tenant:
    type: int
    default: 40
    description: |
      Default maximum volume capacity (in GB) spanning across all Trove volumes
      per tenant.
  max-backups-per-tenant:
    type: int
    default: 50
    description: |
      Default maximum number of backups created by a tenant.
  max-instances-per-tenant:
    type: int
    default: 10
    description: |
      Default maximum number of instances per tenant.
  nova-keypair:
    type: string
    default: ""
    description: |
      Name of a Nova keypair to inject into a database instance to enable SSH
      access. The keypair should be prior created by the cloud operator.
  default-datastore:
    type: string
    default: ""
    description: |
      The default datastore ID or name to use if one is not provided by the user.
      If not set, the field becomes required in the instance create request.
  reboot-timeout:
    type: int
    default: 120
    description: |
      Maximum time (in seconds) to wait for a server reboot.
  usage-timeout:
    type: int
    default: 1800
    description: |
      Maximum time (in seconds) to wait for Trove instance to become ACTIVE for creation.
  cluster-usage-timeout:
    type: int
    default: 36000
    description: |
      Maximum time (in seconds) to wait for a cluster to become active.
  restore-usage-timeout:
    type: int
    default: 3600
    description: |
      Maximum time (in seconds) to wait for Trove instance to become ACTIVE for restore.
  agent-call-high-timeout:
    type: int
    default: 180
    description: |
      Maximum time (in seconds) to wait for Guest Agent ‘slow’ requests
      (such as restarting the instance server) to complete.
  agent-replication-snapshot-timeout:
    type: int
    default: 1800
    description: |
      Maximum time (in seconds) to wait for taking a Guest Agent replication snapshot.

  # Trove Guest Agent config options.
  container-registry:
    type: string
    default: ""
    description: |
      URL to the registry. E.g. https://index.docker.io/v1/
  container-registry-username:
    type: string
    default: ""
    description: |
      The registry username.
  container-registry-password:
    type: string
    default: ""
    description: |
      The plaintext registry password.
